platform :ios, '11.0'

target 'SDKSample-ObjectiveC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SDKSample-ObjectiveC
  pod 'SenselySDK', '~>3.3.9'
end
